// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wavmbkruruokmuvsxtkb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indhdm1ia3J1cnVva211dnN4dGtiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4MjY2NzEsImV4cCI6MjA3MTQwMjY3MX0.03CAFByfDHMWmQrz7LBM6Fy4aKCYYsVIiIUvTdJCmJI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});